services:
  postgres:
    image: postgres:16-alpine
    container_name: petromallis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: petromallis
      POSTGRES_PASSWORD: petromallis_secret
      POSTGRES_DB: petromallis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petromallis -d petromallis_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
