"""add_status_power_brand_categories_matches

Revision ID: 98c7f0486bb4
Revises: b526d9a8f077
Create Date: 2026-06-16 20:49:17.742736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c7f0486bb4'
down_revision: Union[str, None] = 'b526d9a8f077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_categories_id'), 'brand_categories', ['id'], unique=False)
    op.create_index(op.f('ix_brand_categories_name'), 'brand_categories', ['name'], unique=True)
    op.create_table('brand_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('radius_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_area_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_area_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_user_id'], ['dealers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['brand_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_requirements_brand_user_id'), 'brand_requirements', ['brand_user_id'], unique=False)
    op.create_index(op.f('ix_brand_requirements_category_id'), 'brand_requirements', ['category_id'], unique=False)
    op.create_index(op.f('ix_brand_requirements_id'), 'brand_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_brand_requirements_status'), 'brand_requirements', ['status'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['brand_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['dealers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_requirement_id'), 'matches', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_matches_space_id'), 'matches', ['space_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.add_column('preferred_brands', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_preferred_brands_category_id'), 'preferred_brands', ['category_id'], unique=False)
    op.create_foreign_key(None, 'preferred_brands', 'brand_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('spaces', sa.Column('power_kw', sa.Float(), nullable=True))
    op.add_column('spaces', sa.Column('water_available', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('spaces', sa.Column('drainage_avail', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('stations', sa.Column('status', sa.String(length=50), server_default='pending', nullable=False))
    op.create_index(op.f('ix_stations_status'), 'stations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_status'), table_name='stations')
    op.drop_column('stations', 'status')
    op.drop_column('spaces', 'drainage_avail')
    op.drop_column('spaces', 'water_available')
    op.drop_column('spaces', 'power_kw')
    op.drop_constraint(None, 'preferred_brands', type_='foreignkey')
    op.drop_index(op.f('ix_preferred_brands_category_id'), table_name='preferred_brands')
    op.drop_column('preferred_brands', 'category_id')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_space_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_requirement_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_brand_requirements_status'), table_name='brand_requirements')
    op.drop_index(op.f('ix_brand_requirements_id'), table_name='brand_requirements')
    op.drop_index(op.f('ix_brand_requirements_category_id'), table_name='brand_requirements')
    op.drop_index(op.f('ix_brand_requirements_brand_user_id'), table_name='brand_requirements')
    op.drop_table('brand_requirements')
    op.drop_index(op.f('ix_brand_categories_name'), table_name='brand_categories')
    op.drop_index(op.f('ix_brand_categories_id'), table_name='brand_categories')
    op.drop_table('brand_categories')
    # ### end Alembic commands ###
